import "./globals.css";
import type { Metadata } from "next";
import { Poppins, Roboto } from "next/font/google";

const poppins = Poppins({
  weight: ["500", "600", "700", "800"],
  variable: "--font-poppins"
});

const roboto = Roboto({
  weight: ["200", "300", "400", "500", "600"],
  variable: "--font-roboto"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}